<?php

// Load Nette Framework or autoloader generated by Composer
require __DIR__ . '/../libs/autoload.php';


$configurator = new Nette\Config\Configurator;

// Enable Nette Debugger for error visualisation & logging
//$configurator->setDebugMode(TRUE);
$configurator->enableDebugger(isset($_ENV['OPENSHIFT_PHP_LOG_DIR']) ? $_ENV['OPENSHIFT_PHP_LOG_DIR'] : __DIR__ . '/../log');

// Specify folder for cache
$configurator->setTempDirectory(isset($_ENV['OPENSHIFT_TMP_DIR']) ? $_ENV['OPENSHIFT_TMP_DIR'] : __DIR__ . '/../temp');

// Enable RobotLoader - this will load all classes automatically
$configurator->createRobotLoader()
	->addDirectory(__DIR__)
	->addDirectory(__DIR__ . '/../libs')
	->register();

// Create Dependency Injection container from config.neon file
$configurator->addConfig(__DIR__ . '/config/config.neon');
$configurator->addConfig(__DIR__ . '/config/config.local.neon', $configurator::NONE); // none section
$container = $configurator->createContainer();

return $container;
